"""Regenerate main.py from the canonical dbt project at ../../dbt.

A MotherDuck Flight can't import a local package or read files from the
repo, so main.py can't `import dbt` and point it at `dbt/` directly —
instead this script embeds every file under `dbt/` as a string constant
in main.py, which writes them out to a temp directory at runtime and
invokes dbt's Python API against that temp project.

`dbt/` is the source of truth for models/tests/config. Never hand-edit the
PROJECT_FILES block in main.py — edit `dbt/` and rerun this script:

    python Flights/marketstack-dbt/generate.py
"""
from __future__ import annotations

import pathlib

HERE = pathlib.Path(__file__).parent
REPO_ROOT = HERE.parent.parent
DBT_PROJECT_DIR = REPO_ROOT / "dbt"

# Files to embed, relative to dbt/. Keep in sync with what's under dbt/.
PROJECT_FILE_NAMES = [
    "dbt_project.yml",
    "profiles.yml",
    "macros/generate_schema_name.sql",
    "models/sources.yml",
    "models/silver_aapl_eod.sql",
    "models/gold_aapl_daily_returns.sql",
    "models/schema.yml",
    "tests/silver_unique_symbol_trade_date.sql",
]

MAIN_PY_TEMPLATE = '''\
"""MotherDuck Flight: build silver_aapl_eod + gold_aapl_daily_returns via dbt.

Runs `dbt build` against the marketstack_test database using dbt-core's
Python API. The dbt project itself lives at dbt/ in the repo (models,
tests, dbt_project.yml, profiles.yml) — PROJECT_FILES below is a generated
embedded copy of it, because a Flight can't import a local package or read
repo files at runtime. Never edit PROJECT_FILES by hand: edit dbt/ and
regenerate this file with generate.py.

This is a local copy of the source currently saved to MotherDuck as the
"marketstack-dbt" Flight. Edit dbt/, run generate.py, then push with:
    update_flight(id=<flight_id>, source_code=...)

Replaces the marketstack-silver and marketstack-gold Flights.
"""
from __future__ import annotations

import pathlib
import tempfile

from dbt.cli.main import dbtRunner

DB = "marketstack_test"

# Generated by generate.py from dbt/ — do not edit by hand.
PROJECT_FILES: dict[str, str] = {project_files!r}


def write_project(root: pathlib.Path) -> None:
    for relative_path, content in PROJECT_FILES.items():
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        project_dir = pathlib.Path(tmp)
        write_project(project_dir)

        # A Flight's own `md:` connection is already authenticated as the
        # Flight's identity, same as duckdb.connect("md:") in the other
        # Flights, so profiles.yml needs no token here. If dbt-duckdb ever
        # needs one explicitly, set `motherduck_token` via a Flight secret
        # and reference it in profiles.yml as {{{{ env_var('motherduck_token') }}}}.
        result = dbtRunner().invoke(
            [
                "build",
                "--project-dir",
                str(project_dir),
                "--profiles-dir",
                str(project_dir),
            ]
        )

    if not result.success:
        raise RuntimeError(f"dbt build failed: {{result.exception or result.result}}")

    for run_result in result.result.results:
        print(f"{{run_result.node.name}}: {{run_result.status}} ({{run_result.execution_time:.1f}}s)")
    print("dbt build succeeded.")


if __name__ == "__main__":
    main()
'''


def main() -> None:
    project_files = {
        name.replace("\\", "/"): (DBT_PROJECT_DIR / name).read_text(encoding="utf-8")
        for name in PROJECT_FILE_NAMES
    }
    main_py = MAIN_PY_TEMPLATE.format(project_files=project_files)
    (HERE / "main.py").write_text(main_py, encoding="utf-8")
    print(f"Wrote {HERE / 'main.py'} from {len(project_files)} file(s) under {DBT_PROJECT_DIR}")


if __name__ == "__main__":
    main()
